const enum ErrorCode {
  // Auth error
  AUTH_EMAIL_ALREADY_EXISTS = 'ATUH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_NOT_FOUND = 'AUTH_NOT_FOUND',
  AUTH_TOO_MANY_ATTEMPTS = 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_UNAUTHORIZED_ACCESS = 'AUTH_UNAUTHORIZED_ACCESS',
  AUTH_USER_DISABLED = 'AUTH_USER_DISABLED',
  AUTH_TOKEN_NOT_FOUND = 'AUTH_TOKEN_NOT_FOUND',

  // Access control errors
  ACCESS_ERROR = 'ACCESS_ERRORS',
  ACCESS_UNAUTHORIZED = 'ACCESS_UNAUTHORIZED',

  // Validation and resource error
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // System error
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VERIFICATION_ERROR = 'VERIFICATION_ERROR'
}
export { ErrorCode }
